### PR TITLE
including some files from populse_mia in Capsul (graphics rendering of pipeline)

### PR DESCRIPTION
**Pull request by montigno**
2 files have been modified : 
	- capsul/qt_gui/widgets/pipeline_developper_view.py	
	- capsul/pipeline/pipeline_tools.py

In the 1st file, the graphics rendering of the blocks has been improved and some bugs have been fixed.
In the 2nd, the definition of colors has been changed.

To determine definitively, it would have to make further tests on your side.

### CODE REVIEW

**Comment by denisri** [comment]
Globally I'm OK with the proposed changes, which provide significant improvements. I had a look at the code changes but didn't check everything (there are lots of changes, you actually worked a lot).

I noticed a few features removal however that raise a few questions. Mainly, in the edition menu some options have disapeared:
* add process in pipeline
* add custom node in pipeline
* save pipeline parameters
* load pipeline parameters
I guess they have been removed because in MIA the drag & drop for processes and parameters tab do replace them, but this makes the widget unusable outside the context of MIA, so maybe these features should be hidden in MIA rather than removed in PipelineDevelopperView ?

Otherwise there are a few imports of PyQt5: we still support Qt4 and have our switch mechanism: soma.qt_gui.qt_backend - I can change this, this is trivial, and python2 tests fail (I think this is due to the use of open(filename, encoding), we can use io.open() so it's not difficult to fix either).

A minor point: pipeline steps position is not always correct, we have to adjust this (I can do that later).

Last point: I could not open a pipeline which contains "custom nodes" (new node types). I think I can fix that also, it should not be a big issue.

I can help for the modifs, I'm just not sure how to propose modifs to a pull request in github...

**Comment by denisri** [comment]
I have a doubt: did you actually merge the pipeline_developper_view.py source file in the current master branch, or did you just replace it with your version, which was a copy at an earlier time ? I'm not sure any of the evolutions of this file since you forked it is still in the source in this pull request...

**Comment by denisri** [comment]
Well, I have the answer: the file in the PR is a copy of the one which was in populse_mia/python/populse_mia/pipeline_manager/capsul_files/pipeline_developper_view.py, the latter one already being a copy of an earlier version. Thus all changes made since the first copy have been wiped out.

Not to blame anybody, but this is not the correct way of working with git. We should not copy files at all (well, almost - or have a very good reason for that) but instead work with branches.
To fix that I will need to have the date (or commit number) when you copied the file into populse_mia, then create a branch from that time, copy the file from the PR in the new branch, and merge with the current master (which may be a bit painful).
I guess the same happened with the other file, pipeline_tools.py.

**Comment by denisri** [comment]
It seems that most of the missing features are actually due to the absence of merging with the recent changes.
I have setup a feature branch "pdview_mia" where I have done the merge. It seems to fix things for me. Can you test it please ? If it's OK this branch would replace the current pull request.
The drawback is that it loses the history of modifications of the files during its journey in the populse_mia project, but it's really complicated to get it back.

**Comment by servoz** [comment]
Sorry for this dirty PR (and for the delay, I was not available yesterday afternoon !).
May be, the best way could be that we remove this PR and I do a new clean PR ?

**Comment by denisri** [comment]
You don't have to be sorry, we all have to learn how to work together with github...
OK then can you check the branch "pdview_mia" ? I have basically merged there the files of this PR with the current master, which (for me) seems to solve many of the issues. (except the add node feature which will have to be adapted afterwards).

**Comment by servoz** [comment]
Just end few checks on this pdview_mia branch and all seems ok !

**Comment by denisri** [comment]
OK then I will push it into master and fix the remaining issues. We can close (abort) this PR.

**Comment by servoz** [comment]
Ok, let me know when the merge will be effective (we have to push the import change on mia !)

**Comment by denisri** [comment]
It's merged.
I have re-enabled "add process" and "open node controller" options, and added a method to setup a "restriced edition" mode which hides these features (pipeline_view.set_restricted_edition_mode(True))

**Comment by servoz** [comment]
Great !

**Pull request closed without merging**
