### PR TITLE
Parsing env variables

### PR DESCRIPTION
**Pull request by servoz**
As discussed in private message, we should put the parse_env_lines() method in soma.utils instead, but in the meantime we can already make the modification in capsul (the method is therefore repeated for each module of capsul.in_context). I don't have freesurfer installed on my computer so I didn't make the modification for the module capsul.in_context.freesurfer, because I can't test the result.

### CODE REVIEW

**Comment by denisri** [comment]
I will merge the PR but here the function is duplicated several times, which will certainly end up with "different" behaviors when we modify/fix one of them. We need to move it in a centralized place soon.

**Comment by denisri** [comment]
I've put it in `soma.utils.env`. I'm moving the calls to it in capsul.

**Comment by denisri** [comment]
it's moved.

**Comment by servoz** [comment]
Thanks @denisri !

**Pull request merged**
