### PR TITLE
Save pipeline parameters only in JSON format

### PR DESCRIPTION
**Pull request by M40V**
Add a class attribute self.clinical_mode to avoid overloading in MIA.

### CODE REVIEW

**Comment by servoz** [comment]
Why add a clinical_mode attribute in a capsul module when it is, a priori, a mia functionality?
May be it is a wish for capsul to have a clinical mode and a developer/super user mode ?

**Comment by M40V** [comment]
Yes, without this attribute, we'll have to overload capsul in mia if we want to make saving over existing files possible in developer mode and impossible in clinical mode.

**Comment by servoz** [comment]
the point is not the attribute, but name ...

**Comment by denisri** [comment]
This is a very minor point but I quite agree with the idea that Capsul has been made generic enough to live out of a context of a "clinical" mode. I'd rather stick with technical considerations here: what we need is a flag to disable overwriting existing files, so it could be named "forbid_overwrite_files", or "disable_overwrite" or something like that. In MIA we can show a "clinical" mode to the end user, which would trigger the use of this flag in Capsul.
However I'm not focused here, if you really prefer to call it "clinical_mode", it's OK for me anyway.

**Comment by servoz** [comment]
Indeed, this is a very minor point, and if the clinical_mode flag name is ok for you, that's right for me. (however, for me capsul doesn't give a shit about clinical mode or not, what it wants is just to know if it allows to overwrite an existing file, or not!)

**Pull request merged**
